Repository openshift/assisted-image-service, pull requests merged in 2021-08, with the labels that each got.

#6 Add setup script to share logic with prow
  Dockerfile.image-service-build
  Makefile
  hack/setup_env.sh
Labels: approved, lgtm, size/S

#5 Add isoeditor from assisted-service to create minimal iso templates
  README.md
  go.mod
  go.sum
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/imagestore/mock_imagestore.go
  pkg/isoeditor/isoeditor_suite_test.go
  pkg/isoeditor/isoutil.go
  pkg/isoeditor/isoutil_test.go
  pkg/isoeditor/mock_editor.go
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#7 Clean up test setup duplication
  pkg/isoeditor/isoeditor_suite_test.go
  pkg/isoeditor/isoutil_test.go
  pkg/isoeditor/rhcos_test.go
Labels: approved, lgtm, size/L

#8 MGMT-7256 Add ISO stream customization
  Makefile
  go.mod
  go.sum
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/imagestore/mock_imagestore.go
  pkg/isoeditor/isoeditor_suite_test.go
  pkg/isoeditor/isoutil.go
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
  pkg/isoeditor/stream.go
  pkg/isoeditor/stream_test.go
  pkg/overlay/overlay.go
  pkg/overlay/overlay_test.go
Labels: approved, size/XL, lgtm

#11 Add build_deploy.sh script to create app-sre image
  build_deploy.sh
Labels: approved, size/S, lgtm

#10 Add pull request template
  .github/pull_request_template.md
Labels: approved, lgtm, size/M

#9 MGMT-7499 Take an auth token as a query parameter and pass it to assisted
  Makefile
  README.md
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
Labels: approved, lgtm, size/L

#12 Rename `Port` to `ListenPort` and document `ASSISTED_SERVICE_HOST` format for clarification
  Makefile
  README.md
  main.go
  skipper.yaml
Labels: approved, size/S, lgtm

#13 build_deploy.sh chmod +x
  build_deploy.sh
Labels: approved, size/XS, lgtm

#14 Use docker for build script instead of podman
  build_deploy.sh
Labels: approved, size/S, lgtm

#16 move to v2 api for discovery ignition
  internal/handlers/images.go
  internal/handlers/images_test.go
Labels: approved, size/S, lgtm

#15 Query initrd content and embed into minimal isos
  internal/handlers/images.go
  internal/handlers/images_test.go
  pkg/isoeditor/stream.go
  pkg/isoeditor/stream_test.go
Labels: approved, lgtm, size/L

#17 Use array format for versions and add image arch support
  README.md
  internal/handlers/images.go
  internal/handlers/images_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/imagestore/mock_imagestore.go
Labels: approved, lgtm, size/L
