Repository openshift/assisted-image-service, pull requests merged in 2021-09, with the labels that each got.

#20 NO-ISSUE: Ignore Dockerfile when copying files to image
  .dockerignore
Labels: approved, size/XS, lgtm

#19 feat: support self-signed certificates on assisted-service
  README.md
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
Labels: approved, lgtm, size/M

#18 Add support for multi-arch base images
  Makefile
  README.md
  internal/handlers/images.go
  internal/handlers/images_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/imagestore/mock_imagestore.go
Labels: approved, lgtm, size/L

#22 MGMT-7762: Pin the UBI version to 8.4
  Dockerfile.image-service
Labels: approved, size/XS, lgtm

#23 Align type values with those from assisted-service
  README.md
  internal/handlers/images_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/M

#21 MGMT-7754: Support iso creation with EFI boot only
  pkg/isoeditor/isoeditor_suite_test.go
  pkg/isoeditor/isoutil.go
  pkg/isoeditor/isoutil_test.go
Labels: approved, lgtm, size/M

#25 MGMT-7762: Switch to stream8
  Dockerfile.image-service
Labels: approved, size/XS, lgtm

#26 NO-ISSUE: Fix typo and formatting in readme
  README.md
Labels: approved, size/S, lgtm

#27 Limit requests in flight for image downloads
  README.md
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
Labels: approved, size/S, lgtm
