Repository openshift/assisted-image-service, pull requests merged in 2021-11, with the labels that each got.

#37 NO-ISSUE: Update owners file
  OWNERS_ALIASES
Labels: approved, size/S, lgtm

#38 MGMT-7897: Rework authentication handling to support image_token
  README.md
  integration_test/images_test.go
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
Labels: approved, lgtm, size/L

#41 MGMT-7716: Add a template to deploy to console.redhat.com
  deploy/template.yaml
Labels: approved, lgtm, size/M

#40 Bug 2023616: Add liveness endpoint
  README.md
  internal/handlers/images_test.go
  internal/handlers/liveness.go
  internal/handlers/readiness.go
  main.go
Labels: approved, bugzilla/severity-medium, lgtm, bugzilla/valid-bug, size/M

#39 MGMT-8216: Handle persistent storage for the data directory
  README.md
  go.mod
  go.sum
  integration_test/images_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/L

#42 Add the ability to customise PXE files
  pkg/isoeditor/initramfs.go
  pkg/isoeditor/initramfs_test.go
  pkg/overlay/overlay.go
  pkg/overlay/overlay_test.go
Labels: approved, lgtm, size/L

#43 Close the ISO file after serving a request
  internal/handlers/images.go
  internal/handlers/images_test.go
  pkg/isoeditor/initramfs.go
  pkg/isoeditor/stream.go
  pkg/overlay/overlay.go
Labels: approved, lgtm, size/M

#44 Use edge-infrastructure image instead of ocpmetal
  Makefile
Labels: approved, size/XS, lgtm
