Repository openshift/assisted-image-service, pull requests merged in 2021-12, with the labels that each got.

#45 MGMT-8306: Use renameio in downloadURLToFile
  go.mod
  go.sum
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/M

#46 Pass the status code through when assisted service request fails
  internal/handlers/images.go
  internal/handlers/images_test.go
Labels: approved, lgtm, size/L

#47 Support OS_IMAGES as well as RHCOS_VERSIONS
  Makefile
  README.md
  main.go
Labels: approved, size/S, lgtm

#48 Add monitoring template for gathering metrics
  deploy/template-monitoring.yaml
  deploy/template.yaml
Labels: approved, lgtm, size/M

#49 Set the Content-Disposition header
  internal/handlers/images.go
  internal/handlers/images_test.go
Labels: approved, size/XS, lgtm

#51 Handle CORS headers properly
  README.md
  go.mod
  go.sum
  internal/handlers/middleware.go
  internal/handlers/middleware_test.go
  main.go
Labels: approved, lgtm, size/L
