Repository openshift/assisted-image-service, pull requests merged in 2022-03, with the labels that each got.

#63 Fix overlay reader for base readers that return EOF early
  pkg/overlay/overlay.go
  pkg/overlay/overlay_test.go
Labels: approved, lgtm, size/M

#62 MGMT-9332: Add endpoint for rootfs and kernel
  README.md
  integration_test/images_test.go
  internal/handlers/boot_artifacts.go
  internal/handlers/boot_artifacts_test.go
  internal/handlers/handlers_suite_test.go
  internal/handlers/images.go
  internal/handlers/images_test.go
  main.go
  pkg/isoeditor/isoutil.go
Labels: approved, lgtm, size/L

#64 MGMT-9333 Add ipxe-initrd endpoint for customized initrd
  README.md
  integration_test/images_test.go
  internal/handlers/assisted_service_client.go
  internal/handlers/boot_artifacts.go
  internal/handlers/boot_artifacts_test.go
  internal/handlers/handlers_suite_test.go
  internal/handlers/images.go
  internal/handlers/images_test.go
  internal/handlers/initrd.go
  internal/handlers/initrd_test.go
  internal/handlers/iso.go
  internal/handlers/iso_test.go
  internal/handlers/log.go
  main.go
Labels: approved, size/XXL, lgtm

#65 MGMT-9019: Download full ISO in parallel, but build the mionimal ISO sequentially
  pkg/imagestore/imagestore.go
  pkg/isoeditor/rhcos.go
Labels: approved, lgtm, size/M

#66 Return a 503 from images and boot-artifacts before downloads finish
  internal/handlers/handlers_suite_test.go
  internal/handlers/readiness.go
  internal/handlers/readiness_test.go
  main.go
Labels: approved, lgtm, size/M

#67 [release-ocm-2.4] Bug 2069806: Use fields from http.DefaultTransport in imagestore
  pkg/imagestore/imagestore.go
Labels: approved, size/S, lgtm, bugzilla/valid-bug, bugzilla/severity-high
