Repository openshift/assisted-image-service, pull requests merged in 2022-01, with the labels that each got.

#52 MGMT-8661: Added openshift_version to image path template
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/M

#54 Add os image entries for 4.10 to imagestore and template
  deploy/template.yaml
  pkg/imagestore/imagestore.go
Labels: approved, size/XS, lgtm

#55 MGMT-8925: allow more size in requested PV to store all images
  deploy/template.yaml
Labels: approved, size/XS, lgtm

#56 MGMT-8927: build image from scratch to handle possible cleanups
  build_deploy.sh
Labels: approved, size/XS, lgtm

#50 isoeditor: support editing FCOS grub.cfg
  integration_test/images_test.go
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
Labels: approved, lgtm, size/M

#53 Bug 2034686: Allow for disabling TLS verification for fetching ISOs
  integration_test/images_test.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/M, bugzilla/severity-high
