Repository openshift/assisted-image-service, pull requests merged in 2022-06, with the labels that each got.

#81 NO-ISSUE: update prometheus client and gomega pkgs
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#80 MGMT-10623: Add OCP 4.11 nightly images
  deploy/template.yaml
  pkg/imagestore/imagestore.go
Labels: approved, lgtm, size/M

#79 Bug 2089195: [release-ocm-2.5] add an option expose all endpoints on plain HTTP port"
  Makefile
  README.md
  internal/handlers/middleware.go
  internal/handlers/middleware_test.go
  main.go
  pkg/servers/servers.go
  pkg/servers/servers_test.go
Labels: approved, bugzilla/severity-medium, lgtm, bugzilla/valid-bug, size/L

#83 MGMT-10751: use boot-artifacts API as rootfs URL
  README.md
  integration_test/images_test.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/L

#84 NO-ISSUE: bump golang to 1.17
  Dockerfile.image-service
  Dockerfile.image-service-build
  go.mod
Labels: approved, size/S, lgtm, do-not-merge/hold
