Repository openshift/assisted-image-service, pull requests merged in 2022-07, with the labels that each got.

#86 Update README.md
  README.md
Labels: approved, size/XS, lgtm

#85 MGMT-11048: add image_service_host var to template
  deploy/template.yaml
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/L

#87 Remove OCP 4.6 from integration environment
  deploy/template.yaml
  pkg/imagestore/imagestore.go
Labels: approved, size/S, lgtm

#88 MGMT-10957: remove fallback for missing imageServiceHost
  Makefile
  README.md
  deploy/template.yaml
  integration_test/images_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/M

#89 MGMT-11124: support IMAGE_SERVICE_BASE_URL env var
  Makefile
  README.md
  deploy/template.yaml
  main.go
Labels: approved, size/S, lgtm
