Repository openshift/assisted-image-service, pull requests merged in 2022-04, with the labels that each got.

#68 MGMT-9538: Only log.Fatal from main in the image service
  integration_test/images_test.go
  internal/handlers/assisted_service_client.go
  internal/handlers/initrd_test.go
  internal/handlers/iso_test.go
  main.go
Labels: approved, lgtm, size/M

#69 Update openssl libs in Dockerfile
  Dockerfile.image-service
Labels: approved, size/XS, lgtm

#72 Set Last-Modified time for iso and initrd downloads
  internal/handlers/assisted_service_client.go
  internal/handlers/initrd.go
  internal/handlers/initrd_test.go
  internal/handlers/iso.go
  internal/handlers/iso_test.go
Labels: approved, lgtm, size/L

#71 Bug 2078531: add an option expose all endpoints on plain HTTP port
  internal/servers/servers.go
  internal/servers/servers_test.go
  main.go
Labels: approved, bugzilla/severity-medium, lgtm, bugzilla/valid-bug, size/L
