Repository openshift/assisted-image-service, pull requests merged in 2022-02, with the labels that each got.

#57 Bug 2046521: Allow for disabling TLS verification for fetching ISOs.
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, bugzilla/valid-bug, size/M, bugzilla/severity-high

#58 NO-ISSUE: Update RHCOS pre-release x86_64 image URL
  integration_test/images_test.go
Labels: approved, size/XS, lgtm

#60 Update go-diskfs dependency
  go.mod
  go.sum
Labels: approved, size/S, lgtm

#61 Use fields from http.DefaultTransport in imagestore
  pkg/imagestore/imagestore.go
Labels: approved, size/XS, lgtm
