Repository openshift/assisted-image-service, pull requests merged in 2022-12, with the labels that each got.

#104 Update go-diskfs to latest
  go.mod
  go.sum
  integration_test/images_test.go
  pkg/isoeditor/isoutil.go
  pkg/isoeditor/isoutil_test.go
  pkg/isoeditor/stream_test.go
Labels: approved, size/S, lgtm

#105 Validate the volume ID for downloaded ISOs
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/M

#106 MGMT-12840: set restricted list of approvers for 2.7
  OWNERS_ALIASES
Labels: approved, size/S, lgtm

#107 MGMT-12548: Return a more graceful error if ASSISTED_SERVICE_HOST not set
  internal/handlers/assisted_service_client.go
  internal/handlers/assisted_service_client_test.go
Labels: approved, size/S, lgtm

#110 AGENT-438: Allow initramfs to be read directly from ISO
  pkg/isoeditor/initramfs.go
Labels: approved, size/S, lgtm

#109 Support ppc64le and s390x
  integration_test/images_test.go
  internal/handlers/iso.go
  internal/handlers/iso_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/isoeditor/mock_editor.go
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
Labels: ok-to-test, approved, lgtm, size/L
