Repository openshift/assisted-image-service, pull requests merged in 2023-07, with the labels that each got.

#127 MGMT-15235: Compile with CGO_ENABLED=1 for FIPS
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference

#131 MGMT-15343: dependabot group updates
  .github/dependabot.yml
Labels: approved, lgtm, size/M, jira/valid-reference

#134 NO-ISSUE: fix for vulnerability GO-S2112
  pkg/servers/servers.go
Labels: approved, size/S, lgtm, jira/valid-reference
