Repository openshift/assisted-image-service, pull requests merged in 2023-04, with the labels that each got.

#119 adds ability to set the log level
  Makefile
  README.md
  main.go
Labels: approved, size/S, lgtm

#120 MGMT-12743: adds support for shorter URLs
  README.md
  go.mod
  go.sum
  integration_test/images_test.go
  internal/handlers/assisted_service_client.go
  internal/handlers/images.go
  internal/handlers/images_test.go
  internal/handlers/initrd.go
  internal/handlers/initrd_test.go
  internal/handlers/iso.go
  internal/handlers/iso_test.go
  internal/handlers/long.go
  internal/handlers/middleware.go
  internal/handlers/short.go
  internal/handlers/short_test.go
  main.go
Labels: approved, size/XXL, lgtm, jira/valid-reference

#122 Remove REQUEST_AUTH_TYPE from Makefile
  Makefile
Labels: approved, size/XS, lgtm
