Repository openshift/assisted-image-service, pull requests merged in 2023-11, with the labels that each got.

#159 MGMT-16077: Add release and OS images for OCP 4.15
  deploy/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#160 NO-ISSUE: Add my github account as owner for this repository
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#161 NO-ISSUE: add rccrdpccl to approvers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#163 MGMT-16239: Use ignition info - ACM 2.9
  pkg/isoeditor/isoeditor_suite_test.go
  pkg/isoeditor/stream.go
  pkg/isoeditor/stream_test.go
Labels: approved, lgtm, size/L, jira/valid-reference
