Repository openshift/assisted-image-service, pull requests merged in 2023-10, with the labels that each got.

#148 NO-ISSUE: add adriengentil as approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#150 MGMT-15507: Set restricted list of approvers for protected release-ocm-2.9 branch
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#152 NO-ISSUE: add me to owners
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#156 MGMT-13692: Use ignition info
  pkg/isoeditor/isoeditor_suite_test.go
  pkg/isoeditor/stream.go
  pkg/isoeditor/stream_test.go
Labels: approved, lgtm, size/L, jira/valid-reference
