Repository openshift/assisted-image-service, pull requests merged in 2024-12, with the labels that each got.

#295 MGMT-19390: Update mce's tekton pipelines to be multi-arch
  .tekton/assisted-image-service-mce-downstream-main-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#297 MGMT-19408: Create tekton pipelines for acm 2.13
  .tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-2-13-push.yaml
Labels: approved, size/XL, lgtm, jira/valid-reference

#301 MGMT-19507: Stop using multi-arch builds in konflux
  .tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-2-13-push.yaml
  .tekton/assisted-image-service-mce-downstream-main-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#305 MGMT-19531: Remove deprecated task sbom-json-check
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
Labels: approved, lgtm, size/M, jira/valid-reference

#306 MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: approved, size/S, lgtm, jira/valid-reference

#312 [release-ocm-2.9] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: approved, size/S, lgtm, jira/valid-reference

#311 MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: approved, size/S, lgtm, jira/valid-reference

#315 [release-ocm-2.12] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: approved, size/S, lgtm, jira/valid-reference

#313 [release-ocm-2.10] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: approved, size/S, lgtm, jira/valid-reference
