Repository openshift/assisted-image-service, pull requests merged in 2024-07, with the labels that each got.

#242 NO-ISSUE: Download rpm packages in a different stage at the build of Dockerfile-build
  Dockerfile.image-service-build
  hack/setup_env.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#248 NO-ISSUE: Fix OWNERS format
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#249 NO-ISSUE: Bump CI root image golang/openshift version
  .ci-operator.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#250 [release-ocm-2.11] NO-ISSUE: Bump CI root image golang/openshift version
  .ci-operator.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#251 [release-ocm-2.10] NO-ISSUE: Bump CI root image golang/openshift version
  .ci-operator.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#252 [release-ocm-2.8] NO-ISSUE: Bump CI root image golang/openshift version
  .ci-operator.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#247 [release-ocm-2.9] NO-ISSUE: Download rpm packages in a different stage at the build of Dockerfile-build
  .ci-operator.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#243 NO-ISSUE: Ensure data dir is writable by UID/GID
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference

#255 [release-ocm-2.8] MGMT-18332: Download rpm packages in a different stage at the build of Dockerfile-build
  Dockerfile.image-service-build
  Makefile
  hack/setup_env.sh
Labels: approved, lgtm, size/M, jira/valid-reference

#256 [release-ocm-2.9] MGMT-18332: Download rpm packages in a different stage at the build of Dockerfile-build
  Dockerfile.image-service-build
  Makefile
  hack/setup_env.sh
Labels: approved, lgtm, size/M, jira/valid-reference

#261 [release-ocm-2.11] MGMT-18332: install gcc, git and openssl-devel required to run lint correctly
  Dockerfile.image-service-build
Labels: approved, size/S, lgtm, jira/valid-reference

#260 MGMT-18332: install gcc, git and openssl-devel required to run lint correctly
  Dockerfile.image-service-build
  a.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#254 NO-ISSUE: Add renovate config to limit number of PR
  renovate.json
Labels: approved, size/S, lgtm, jira/valid-reference

#258 NO-ISSUE: Allow goup root to write into data dir
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference

#264 MGMT-18385 - updating golang to 1.21
  Dockerfile.image-service
Labels: approved, size/XS, lgtm

#266 MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.image-service
  a.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#267 [release-ocm-2.11] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference

#269 [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.image-service
Labels: approved, size/S, lgtm, jira/valid-reference

#270 [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.image-service
Labels: approved, size/S, lgtm, jira/valid-reference
