Repository openshift/assisted-image-service, pull requests merged in 2024-03, with the labels that each got.

#186 Pad ignition archive to align to word boundary
  internal/handlers/initrd_test.go
  pkg/isoeditor/ignition.go
  pkg/isoeditor/ignition_test.go
  pkg/isoeditor/initramfs_test.go
Labels: approved, size/S, lgtm

#187 MGMT-17308: Offboard osherdp from maintainers list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#188 NO-ISSUE: Refactor to use isoeditor library internally for initrd
  internal/handlers/initrd.go
  pkg/isoeditor/initramfs.go
Labels: approved, size/S, lgtm, jira/valid-reference

#185 MULTIARCH-2678, OCPBUGS-14478: Add a NewIgnitionImageReader() function
  pkg/isoeditor/ignition_image.go
  pkg/isoeditor/ignition_image_test.go
  pkg/isoeditor/stream.go
Labels: approved, lgtm, size/L, jira/severity-important, jira/valid-bug, jira/valid-reference
