Repository openshift/assisted-image-service, pull requests merged in 2024-06, with the labels that each got.

#212 [release-ocm-2.9] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference

#213 [release-ocm-2.8] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference

#211 MULTIARCH-4515i: provide initrd.addrsize endpoint through isoeditor
  internal/handlers/initrd_addrsize.go
  pkg/isoeditor/initrd_addrsize.go
  pkg/isoeditor/initrd_addrsize_test.go
  pkg/isoeditor/isoeditor_suite_test.go
Labels: ok-to-test, approved, lgtm, size/L

#215 [release-ocm-2.11] MGMT-18187: Reduce the list of approvers for ocm-2.11
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#218 NO-ISSUE: Add pastequo as approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#231 KONFLUX-1611: Add labels, licenses & user to Dockerfile
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
  Dockerfile.image-service
Labels: approved, lgtm, size/M, jira/valid-reference
