Repository openshift/assisted-image-service, pull requests merged in 2024-01, with the labels that each got.

#173 NO-ISSUE remove filanov from approves
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#172 MGMT-16507: Enable image service to use additional ca certificates
  integration_test/images_test.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#175 MGMT-16507: Fix incorrect reference to ImageStore
  main.go
Labels: approved, size/S, lgtm, jira/valid-reference
