Repository openshift/assisted-image-service, pull requests merged in 2024-11, with the labels that each got.

#280 MGMT-18577: fetch nmstate binary from rootfs
  Dockerfile.image-service
  Dockerfile.image-service-build
  deploy/template.yaml
  go.mod
  go.sum
  integration_test/images_test.go
  internal/common/version.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/isoeditor/isoutil.go
  pkg/isoeditor/mock_editor.go
  pkg/isoeditor/mock_executer.go
  pkg/isoeditor/mock_nmstate_handler.go
  pkg/isoeditor/nmstate_handler.go
  pkg/isoeditor/nmstate_handler_test.go
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#286 MGMT-18577: Change the minimal version for nmstate
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#288 MGMT-19271: Using CPIO as an alternative approach to extract the rootfs instead of p7zip
  Dockerfile.image-service
  Dockerfile.image-service-build
  pkg/isoeditor/nmstate_handler.go
Labels: approved, size/S, lgtm, jira/valid-reference

#291 MGMT-19371: Add downstream dockerfile for mce
  Dockerfile.image-service-mce
Labels: approved, lgtm, size/M, jira/valid-reference
