Repository openshift/assisted-image-service, pull requests merged in 2024-10, with the labels that each got.

#279 [release-ocm-2.12] MGMT-18932: Reduce the owners list
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#281 MGMT-19128: Migrate assisted-image-service to Konflux
  build_deploy.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#283 MGMT-18693: Change efiLoadSectors block size
  pkg/isoeditor/isoutil.go
  pkg/isoeditor/isoutil_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#285 MGMT-19174: Add rpms-signature-scan to Konflux pipeline
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
Labels: approved, lgtm, size/M, jira/valid-reference
