Repository openshift/assisted-image-service, pull requests merged in 2024-05, with the labels that each got.

#201 OCPBUGS-33240: Skip fat32 log traces when retrieving the ISO file system in the isoeditor package
  pkg/isoeditor/isoutil.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#198 MULTIARCH-4515: Add support for ins-file as boot artefact.
  README.md
  internal/handlers/boot_artifacts.go
  internal/handlers/boot_artifacts_test.go
  internal/handlers/handlers_suite_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: ok-to-test, approved, lgtm, size/M, jira/valid-reference

#206 MULTIARCH-4515: add new endpoint to receive initrd.addrsize
  README.md
  internal/handlers/handlers_suite_test.go
  internal/handlers/images.go
  internal/handlers/images_test.go
  internal/handlers/initrd.go
  internal/handlers/initrd_addrsize.go
  internal/handlers/initrd_addrsize_test.go
  main.go
Labels: approved, lgtm, size/L, jira/valid-reference
