Repository openshift/assisted-image-service, pull requests merged in 2024-02, with the labels that each got.

#177 MGMT-16629: Use custom query params and headers for OS image downloads
  integration_test/images_test.go
  main.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#178 MGMT-16952: Make sure default CA's are preserved when using custom CA
  pkg/imagestore/imagestore.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#180 MGMT-17006: Fix incorrect env var names used for osImageDownloadHeadersMap and osImageDownloadQueryParamsMap
  main.go
Labels: approved, size/S, lgtm, jira/valid-reference

#182 [release-ocm-2.10] MGMT-16878: Set restricted list of approvers
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference
