Repository openshift/assisted-image-service, pull requests merged in 2025-03, with the labels that each got.

#340 NO-ISSUE: Add `dump.erofs` to the image
  .gitignore
  Dockerfile.image-service
  Dockerfile.image-service-mce
  packages/README.md
  packages/build.sh
  packages/erofs-utils/build.sh
  packages/erofs-utils/erofs-utils-1.8.5.tar.gz
  packages/xz/build.sh
  packages/xz/xz-5.6.2.tar.gz
  rpm-prefetching/rpms.in.yaml
  rpm-prefetching/rpms.lock.yaml
Labels: approved, size/XXL, lgtm, jira/valid-reference

#358 NO-ISSUE: Update rpms.lock.yaml
  rpm-prefetching/rpms.lock.yaml
Labels: approved, lgtm, size/L, jira/valid-reference

#357 NO-ISSUE: Fix Konflux configuration for ocm-2.14
  .tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-14-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#359 NO-ISSUE: Fix unit-test downloading ISO from pre-release stream which its path has changed
  integration_test/images_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#355 OCPBUGS-51209: Fixing artifact name issue for vmlinuz in latest rhelVersions
  internal/handlers/boot_artifacts.go
  internal/handlers/boot_artifacts_test.go
Labels: approved, lgtm, size/M, jira/severity-important, jira/valid-bug, jira/valid-reference

#372 [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#371 NO-ISSUE: Remove Eran Ifrach account from OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#377 [release-ocm-2.10] NO-ISSUE: Update OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#378 [release-ocm-2.9] NO-ISSUE: Update OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#368 MGMT-20149: Add sast required tasks in Konflux
  .tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-14-push.yaml
  .tekton/assisted-image-service-acm-ds-main-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-main-push.yaml
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
Labels: approved, size/XL, lgtm, jira/valid-reference

#369 MGMT-20149: Add required SAST tasks
  .tekton/assisted-image-service-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-13-push.yaml
Labels: approved, lgtm, size/L, jira/valid-reference
