Repository openshift/assisted-image-service, pull requests merged in 2025-05, with the labels that each got.

#390 ci: Apply Konflux migration
  .tekton/assisted-image-service-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-13-push.yaml
  .tekton/assisted-image-service-acm-ds-main-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-main-push.yaml
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
Labels: size/XXL

#400 MGMT-20597: Add nmstatectl to initrd for PXE provisioning
  internal/handlers/initrd.go
  internal/handlers/initrd_addrsize_test.go
  internal/handlers/initrd_test.go
  pkg/imagestore/imagestore.go
  pkg/imagestore/imagestore_test.go
  pkg/imagestore/mock_imagestore.go
  pkg/isoeditor/mock_editor.go
  pkg/isoeditor/mock_nmstate_handler.go
  pkg/isoeditor/nmstate_handler.go
  pkg/isoeditor/nmstate_handler_test.go
  pkg/isoeditor/rhcos.go
  pkg/isoeditor/rhcos_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#405 Workflows
  .github/workflows/override_context.yaml
  pkg/imagestore/imagestore_test.go
Labels: approved, lgtm, size/M
