Repository openshift/assisted-image-service, pull requests merged in 2025-01, with the labels that each got.

#318 MGMT-19381: Change downstream base image to rhel9.4 instead of ubi9
  Dockerfile.image-service-mce
Labels: approved, size/XS, lgtm, jira/valid-reference

#321 MGMT-19645: Configure a few things for releasing in konflux
  .tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-2-13-push.yaml
  .tekton/assisted-image-service-mce-downstream-main-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-main-push.yaml
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
  Dockerfile.image-service-mce
  rpm-prefetching/README.md
  rpm-prefetching/rpms.in.yaml
  rpm-prefetching/rpms.lock.yaml
Labels: approved, lgtm, size/L, jira/valid-reference

#323 MGMT-19734: Tune renovate config to enable auto merge
  renovate.json
Labels: approved, size/XS, lgtm, jira/valid-reference

#324 NO-ISSUE: Update buildah image to fix a bug with SBOM
  .tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-2-13-push.yaml
  .tekton/assisted-image-service-mce-downstream-main-pull-request.yaml
  .tekton/assisted-image-service-mce-downstream-main-push.yaml
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#328 MGMT-19819: Add the commit reference from which the image is built to the image
  .dockerignore
  Dockerfile.image-service
Labels: approved, size/XS, lgtm, jira/valid-reference
