Repository openshift/assisted-image-service, pull requests merged in 2025-06, with the labels that each got.

#413 NO-ISSUE: Modify Konflux YAMLs to ocm-2.15
  .tekton/assisted-image-service-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-15-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#416 NO-ISSUE: Add konflux service account migration
  .tekton/assisted-image-service-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-15-push.yaml
Labels: ok-to-test, approved, size/XS, lgtm, jira/valid-reference

#415 NO-ISSUE: CI Konflux SA migration
  .tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-14-push.yaml
Labels: ok-to-test, approved, size/XS, lgtm, jira/valid-reference

#417 NO-ISSUE: Test
  pkg/imagestore/imagestore.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#421 ACM-21380: Make ACM builds multi-arch
  .tekton/assisted-image-service-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-15-push.yaml
  .tekton/assisted-image-service-acm-ds-main-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#427 MGMT-20858: apply tags migration
  .tekton/assisted-image-service-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-13-push.yaml
Labels: approved, lgtm, size/M, jira/valid-reference

#428 MGMT-20858: apply tags migration
  .tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-2-14-push.yaml
  .tekton/assisted-image-service-acm-ds-main-pull-request.yaml
  .tekton/assisted-image-service-acm-ds-main-push.yaml
  .tekton/assisted-image-service-saas-main-pull-request.yaml
  .tekton/assisted-image-service-saas-main-push.yaml
Labels: approved, size/XXL, lgtm, jira/valid-reference
